# Generated by Django 2.2.4 on 2019-08-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiWeather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
