# Generated by Django 2.2.4 on 2019-08-12 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiWeather', '0005_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
